import {
  searchSCRBRepository,
  generateInvestigationStrategy,
  detectContradictions,
  calculateEvidenceReliability,
  getReasoningTree
} from './scrbRepository';

const RESPONSES_KN = {
  no_case: "ಯಾವುದೇ ಸಕ್ರಿಯ ಪ್ರಕರಣವನ್ನು ಲೋಡ್ ಮಾಡಲಾಗಿಲ್ಲ. ದಯವಿಟ್ಟು ಪ್ರಕರಣವನ್ನು ಆಯ್ಕೆಮಾಡಿ.",
  confidence_label: "ವಿಶ್ವಾಸಾರ್ಹತೆ ಮಟ್ಟ",
  unsupported: "ಸೂಚಿಸಲಾದ ಪ್ರಶ್ನೆಗೆ ಸೂಕ್ತ ಉತ್ತರ ಲಭ್ಯವಿಲ್ಲ. ದಯವಿಟ್ಟು ನಿಮ್ಮ ಪ್ರಶ್ನೆಯನ್ನು ಸ್ಪಷ್ಟಪಡಿಸಿ.",
  no_evidence: "ಯಾವುದೇ ಪೋಷಕ ಪುರಾವೆಗಳಿಲ್ಲ.",
  no_matches: "ಹೋಲುವ ಐತಿಹಾಸಿಕ ಪ್ರಕರಣಗಳು ಕಂಡುಬಂದಿಲ್ಲ."
};

/**
 * Synchronous Rule-Based Fallback Copilot Response.
 * Used when offline, API key is missing, or network fails.
 */
export const askCopilotRuleBased = (questionText, currentCase, allCases = [], lang = "en", chatHistory = []) => {
  if (!currentCase) {
    return {
      answer: lang === "kn" ? RESPONSES_KN.no_case : "No case is currently loaded.",
      evidence: "N/A",
      matches: "N/A",
      guideline: "N/A",
      precedent: "N/A",
      reasoning: "Workspace empty.",
      confidence: "Needs verification",
      next_action: "Please load a case."
    };
  }

  let query = (questionText || "").toLowerCase().trim();
  const type = currentCase.incident_type || "Cyber Fraud";

  const scrbResults = searchSCRBRepository(currentCase);
  const strategy = generateInvestigationStrategy(currentCase);
  const contradictions = detectContradictions(currentCase, allCases);
  const reliability = calculateEvidenceReliability(currentCase);
  const reasoningTree = getReasoningTree(currentCase);

  const ents = currentCase.entities || {};
  const phoneList = (ents.phones || []).join(', ') || 'N/A';
  const upiList = (ents.upi_ids || []).join(', ') || 'N/A';
  const bankList = (ents.bank_accounts || []).join(', ') || 'N/A';
  const vehicleList = (ents.vehicles || []).join(', ') || 'N/A';
  const victimName = currentCase.victim || ents.names?.[0] || 'Complainant';
  const suspectList = (currentCase.suspects || []).join(', ') || 'Unidentified suspect';
  const summaryText = currentCase.summary || 'Incident reported to police.';
  const nextActionText = strategy.immediate_actions?.[0]?.recommendation || 'Verify complaint parameters.';

  let answer = "";
  let evidence = "Primary complaint narrative logs.";
  let matches = scrbResults.landmarks.map(m => m.id).join(", ") || "No matches.";
  let guideline = scrbResults.guidelines.map(g => `${g.title} SOP`).join("; ") || "No guideline SOP found.";
  let precedent = scrbResults.precedents.map(p => p.relevant_principle).join("; ") || "No principles matched.";
  let reasoning = "Decisions generated by evaluating timeline and case parameters.";
  let confidence = "Likely";
  let next_action = nextActionText;

  // ── Specific Natural Language Intent Handlers ──────────────────────────────
  if (query.includes("finding") || query.includes("main finding") || query.includes("key finding")) {
    answer = `Key Investigation Findings for Case ${currentCase.id}:

1. Primary Incident Finding:
Incident classified as '${type}' involving victim ${victimName}. ${summaryText}

2. Evidence & Identifier Findings:
Extracted digital footprints include: ${upiList !== 'N/A' ? 'UPI Handle: ' + upiList + '; ' : ''}${phoneList !== 'N/A' ? 'Phone: ' + phoneList + '; ' : ''}${bankList !== 'N/A' ? 'Bank Account: ' + bankList + '; ' : ''}${vehicleList !== 'N/A' ? 'Vehicle: ' + vehicleList + '; ' : ''} Primary evidence points to online impersonation and fraudulent fund collection.

3. Procedural & Priority Findings:
The highest priority action is: ${nextActionText} Immediate preservation of chat screenshots and bank transaction logs under Sec 65B is required.`;

    evidence = `Findings supported by: ${upiList !== 'N/A' ? 'UPI (' + upiList + '), ' : ''}${phoneList !== 'N/A' ? 'Phone (' + phoneList + '), ' : ''}Complaint Statements`;
    reasoning = `Synthesized key investigation findings for case ${currentCase.id} from entity extraction, timeline events, and strategy recommendations.`;

  } else if (query.includes("fact") || query.includes("important fact") || query.includes("key fact")) {
    answer = `Key Facts Logged for Case ${currentCase.id}:

• Complaint File ID: ${currentCase.id}
• Category & Type: ${type}
• Victim / Complainant: ${victimName}
• Suspect Info: ${suspectList}
• Extracted Communications: ${phoneList !== 'N/A' ? 'Phone ' + phoneList : 'N/A'}
• Payment Identifiers: ${upiList !== 'N/A' ? 'UPI ' + upiList : bankList !== 'N/A' ? 'Bank ' + bankList : 'N/A'}
• Summary of Incident: ${summaryText}`;

    evidence = `Verified facts from complaint file ${currentCase.id}`;

  } else if (query.includes("three") || query.includes("3") || query.includes("important point")) {
    answer = `Three Major Important Points for Case ${currentCase.id}:

1. Incident Classification & Modus Operandi:
Registered as '${type}' involving victim ${victimName}. ${summaryText}

2. Primary Digital & Financial Evidence:
Key extracted indicators include ${upiList !== 'N/A' ? 'UPI Handle: ' + upiList + '; ' : ''}${phoneList !== 'N/A' ? 'Phone: ' + phoneList + '; ' : ''}${bankList !== 'N/A' ? 'Bank Account: ' + bankList + '; ' : ''}${vehicleList !== 'N/A' ? 'Vehicle: ' + vehicleList + '; ' : ''} for tracing the offender.

3. Immediate Investigative Priority:
Suggested priority action: ${nextActionText} Secure certified statements and freeze beneficiary accounts under Sec 65B.`;

    evidence = `Supported by extracted entities and complaint narrative logs.`;

  } else if (query.includes("summary") || query.includes("summarize") || query.includes("overview")) {
    answer = `Executive Summary for Case ${currentCase.id}:
Case ${currentCase.id} is an active ${type} investigation initiated by ${victimName}. ${summaryText} Suspect indicators log contact numbers (${phoneList}) and payment routes (${upiList}). Primary next step: ${nextActionText}`;

  } else if (query === "why?" || query === "why" || query.includes("explain why") || query.includes("reason")) {
    answer = `Advisory reasoning path details: The recommendation of "${nextActionText}" is proposed based on active guidelines. Node traces follow: Complaint -> Entities -> Timeline -> Evidence -> Decision.`;
    reasoning = reasoningTree.map(n => n.evidence_trace).join(" -> ");

  } else if (query === "show more." || query === "show more" || query.includes("more detail") || query.includes("detail")) {
    answer = `Expanding current assessment for Case ${currentCase.id}: Suggested procedure is to immediately document and secure call detail records (CDR) and trace IP logins of siphoning UPI handles.`;
    next_action = "Liaise with Nodal officers to secure suspect gateway logs.";

  } else if (query.includes("do next") || query.includes("next step") || query.includes("action")) {
    answer = `Based on case completion indices for ${currentCase.id}, the suggested next step is: ${nextActionText}`;
    next_action = nextActionText;

  } else if (query.includes("suspect") || query.includes("perpetrator") || query.includes("who did")) {
    answer = `Suspect profile for Case ${currentCase.id}: Logged suspects include ${suspectList}. Suspect tactics indicate ${type} operating vectors using disposable communication channels.`;
    evidence = `Suspect descriptors & contact handles: ${phoneList !== 'N/A' ? phoneList : suspectList}`;

  } else if (query.includes("victim") || query.includes("complainant")) {
    answer = `Victim details for Case ${currentCase.id}: The primary victim/complainant is ${victimName}. Case category: ${type}.`;

  } else if (query.includes("timeline") || query.includes("sequence") || query.includes("when") || query.includes("chronology")) {
    answer = `Reconstructed timeline for Case ${currentCase.id}: ${(currentCase.timeline || []).map(t => typeof t === 'string' ? t : (t.date ? t.date + ': ' : '') + t.event).join(' → ')}`;

  } else if (query.includes("contradiction") || query.includes("conflict")) {
    if (contradictions.length > 0) {
      answer = `Anomalies identified in Case ${currentCase.id}: ${contradictions.map(c => c.contradiction).join(" · ")}. Details: ${contradictions.map(c => c.reason).join(" · ")}.`;
      evidence = contradictions.map(c => c.supporting_evidence).join("; ");
      confidence = "Needs verification";
    } else {
      answer = `No timeline contradictions or sequence conflicts detected in Case ${currentCase.id}.`;
    }

  } else if (query.includes("evidence") || query.includes("support") || query.includes("weak")) {
    answer = `Supporting evidence analysis for Case ${currentCase.id}: Missing evidence items include ${reliability.missing_evidence.join(", ") || "none"}.`;
    evidence = `Cabinet includes: ${reliability.evidence_scores.map(s => s.name).join(", ") || "None"}.`;

  } else if (query.includes("similar") || query.includes("historical") || query.includes("previous")) {
    answer = `Similarity analysis for Case ${currentCase.id}: Matched ${scrbResults.landmarks.length} similar landmark cases in SCRB memory repository. Key MO matches: ${type} patterns.`;
    next_action = scrbResults.landmarks[0]?.next_steps || "Inspect previous lessons.";

  } else {
    answer = `Investigative summary for Case ${currentCase.id}: This is a ${type} incident concerning ${victimName}. Key evidence parameters logged include ${phoneList !== 'N/A' ? 'Phone: ' + phoneList : ''} ${upiList !== 'N/A' ? 'UPI: ' + upiList : ''}. Recommended next step: ${nextActionText}`;
  }

  if (lang === "kn") {
    return {
      answer: `[ಕನ್ನಡ] ${answer}`,
      evidence: `ಪುರಾವೆ: ${evidence}`,
      matches: `ಹೊಂದಾಣಿಕೆಗಳು: ${matches}`,
      guideline: `ಮಾರ್ಗಸೂಚಿ: ${guideline}`,
      precedent: `ಪೂರ್ವನಿದರ್ಶನ: ${precedent}`,
      reasoning: `ತಾರ್ಕಿಕ ವಿವರಣೆ: ${reasoning}`,
      confidence: `ವಿಶ್ವಾಸಾರ್ಹತೆ: ${confidence}`,
      next_action: `ಮುಂದಿನ ಕ್ರಮ: ${next_action}`
    };
  }

  return {
    answer,
    evidence,
    matches,
    guideline,
    precedent,
    reasoning,
    confidence,
    next_action
  };
};

/**
 * Conversational Investigation Copilot with Live Gemini AI Integration & Offline Fallback.
 */
export const askCopilot = async (questionText, currentCase, allCases = [], lang = "en", chatHistory = []) => {
  if (!currentCase) {
    return askCopilotRuleBased(questionText, currentCase, allCases, lang, chatHistory);
  }

  const proxyUrl = import.meta.env.VITE_CATALYST_PROXY_URL || '/server/geminiProxy';

  // Pre-calculate structured context from CrimeLens internal engines
  const scrbResults = searchSCRBRepository(currentCase);
  const strategy = generateInvestigationStrategy(currentCase);
  const contradictions = detectContradictions(currentCase, allCases);
  const reliability = calculateEvidenceReliability(currentCase);
  const reasoningTree = getReasoningTree(currentCase);

  const prompt = `System: You are CrimeLens Copilot, an AI-assisted reasoning layer for the Karnataka State Police (KSP) investigation workspace.

RULES & POLICY:
1. You NEVER solve cases, determine guilt, make legal conclusions, or name suspects as criminals.
2. NEVER use forbidden words: "guilty", "criminal", "solved", "confirmed", "proved", "definitely".
3. Use ONLY advisory and probabilistic language: "suggested", "likely", "possible", "may indicate", "requires verification", "advisory".
4. The CrimeLens internal engines provided below are the primary source of truth. Explain and summarize their findings clearly.
5. Tailor your response heading and content directly to the officer's question:
   - If asked for "main findings" or "key findings": Provide a "Key Investigation Findings for Case [ID]" breakdown.
   - If asked for "important facts": Provide a "Key Facts Logged for Case [ID]" breakdown.
   - If asked for "three major points": Provide a "Three Major Important Points for Case [ID]" breakdown.
   - If asked to "summarize": Provide an "Executive Summary for Case [ID]".
6. ALWAYS remind the user: "The AI assists. The investigating officer remains the final decision maker."
7. Keep response concise (under 250 words).

STRUCTURED CRIMELENS ENGINE OUTPUTS:
- Case ID: ${currentCase.id} (${currentCase.incident_type || 'General'})
- Summary: ${currentCase.summary || 'N/A'}
- Victim: ${currentCase.victim || 'Complainant'}
- Suspects: ${JSON.stringify(currentCase.suspects || [])}
- Extracted Entities: ${JSON.stringify(currentCase.entities || {})}
- Timeline Events: ${JSON.stringify(currentCase.timeline || [])}
- Historical Landmark Matches: ${JSON.stringify(scrbResults.landmarks.map(l => ({ id: l.id, title: l.title, similarity: l.similarity })))}
- Police Guidelines / SOPs: ${JSON.stringify(scrbResults.guidelines.map(g => g.title))}
- Legal Precedents / Principles: ${JSON.stringify(scrbResults.precedents.map(p => ({ title: p.title, principle: p.relevant_principle })))}
- Strategy Recommendations: ${JSON.stringify(strategy.immediate_actions || [])}
- Contradictions Detected: ${JSON.stringify(contradictions || [])}
- Evidence Reliability / Missing Evidence: ${JSON.stringify(reliability.missing_evidence || [])}

OFFICER QUESTION: "${questionText}"
RESPONSE LANGUAGE: ${lang === 'kn' ? 'Kannada' : 'English'}

Return ONLY a valid JSON object matching this schema. Do NOT use markdown code fences.
{
  "answer": "Case-specific natural language answer directly addressing the officer's question.",
  "evidence": "Brief list of supporting evidence items.",
  "matches": "${scrbResults.landmarks.map(m => m.id).join(', ') || 'None'}",
  "guideline": "${scrbResults.guidelines.map(g => g.title).join('; ') || 'Standard SOP'}",
  "precedent": "${scrbResults.precedents.map(p => p.relevant_principle).join('; ') || 'Standard Procedure'}",
  "reasoning": "Explanation of the reasoning chain from CrimeLens engines.",
  "confidence": "Likely",
  "next_action": "${strategy.immediate_actions?.[0]?.recommendation || 'Verify complaint parameters.'}"
}`;

  try {
    const res = await fetch(proxyUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        action: 'copilot',
        prompt
      })
    });

    if (!res.ok) throw new Error(`HTTP ${res.status}`);

    const result = await res.json();
    if (result && result.success && result.data) {
      const parsed = result.data;
      return {
        answer: parsed.answer || "Advisory summary available from CrimeLens engines.",
        evidence: parsed.evidence || "Primary complaint logs.",
        matches: parsed.matches || scrbResults.landmarks.map(m => m.id).join(", "),
        guideline: parsed.guideline || scrbResults.guidelines.map(g => `${g.title} SOP`).join("; "),
        precedent: parsed.precedent || scrbResults.precedents.map(p => p.relevant_principle).join("; "),
        reasoning: parsed.reasoning || "Reasoning chain evaluated from parameters.",
        confidence: parsed.confidence || "Likely",
        next_action: parsed.next_action || strategy.immediate_actions?.[0]?.recommendation || "Verify parameters."
      };
    }
  } catch (err) {
    console.warn("[CrimeLens Copilot] Catalyst geminiProxy call failed — falling back to internal rule-based engine:", err.message);
  }

  // Fallback to internal rule-based copilot
  return askCopilotRuleBased(questionText, currentCase, allCases, lang, chatHistory);
};
