import {
  searchSCRBRepository,
  generateInvestigationStrategy,
  detectContradictions,
  calculateEvidenceReliability,
  getReasoningTree
} from './scrbRepository';

const RESPONSES_KN = {
  no_case: "ಯಾವುದೇ ಸಕ್ರಿಯ ಪ್ರಕರಣವನ್ನು ಲೋಡ್ ಮಾಡಲಾಗಿಲ್ಲ. ದಯವಿಟ್ಟು ಪ್ರಕರಣವನ್ನು ಆಯ್ಕೆಮಾಡಿ.",
  confidence_label: "ವಿಶ್ವಾಸಾರ್ಹತೆ ಮಟ್ಟ",
  unsupported: "ಸೂಚಿಸಲಾದ ಪ್ರಶ್ನೆಗೆ ಸೂಕ್ತ ಉತ್ತರ ಲಭ್ಯವಿಲ್ಲ. ದಯವಿಟ್ಟು ನಿಮ್ಮ ಪ್ರಶ್ನೆಯನ್ನು ಸ್ಪಷ್ಟಪಡಿಸಿ.",
  no_evidence: "ಯಾವುದೇ ಪೋಷಕ ಪುರಾವೆಗಳಿಲ್ಲ.",
  no_matches: "ಹೋಲುವ ಐತಿಹಾಸಿಕ ಪ್ರಕರಣಗಳು ಕಂಡುಬಂದಿಲ್ಲ."
};

/**
 * Synchronous Rule-Based Fallback Copilot Response.
 * Used when offline, API key is missing, or network fails.
 */
export const askCopilotRuleBased = (questionText, currentCase, allCases = [], lang = "en", chatHistory = []) => {
  if (!currentCase) {
    return {
      answer: lang === "kn" ? RESPONSES_KN.no_case : "No case is currently loaded.",
      evidence: "N/A",
      matches: "N/A",
      guideline: "N/A",
      precedent: "N/A",
      reasoning: "Workspace empty.",
      confidence: "Needs verification",
      next_action: "Please load a case."
    };
  }

  let query = (questionText || "").toLowerCase().trim();
  const type = currentCase.incident_type || "Unknown";

  const scrbResults = searchSCRBRepository(currentCase);
  const strategy = generateInvestigationStrategy(currentCase);
  const contradictions = detectContradictions(currentCase, allCases);
  const reliability = calculateEvidenceReliability(currentCase);
  const reasoningTree = getReasoningTree(currentCase);

  let isFollowUp = false;
  let followUpTopic = "";

  if (query === "why?" || query === "why" || query.includes("explain why") || query.includes("reason")) {
    isFollowUp = true;
    followUpTopic = "reasoning";
  } else if (query === "show more." || query === "show more" || query.includes("more detail") || query.includes("detail")) {
    isFollowUp = true;
    followUpTopic = "more";
  } else if (query.includes("contradiction") || query.includes("conflict")) {
    isFollowUp = true;
    followUpTopic = "contradictions";
  } else if (query.includes("evidence") || query.includes("support")) {
    isFollowUp = true;
    followUpTopic = "evidence";
  } else if (query.includes("similar") || query.includes("historical")) {
    isFollowUp = true;
    followUpTopic = "similar";
  }

  let answer = "";
  let evidence = "Primary complaint narrative logs.";
  let matches = scrbResults.landmarks.map(m => m.id).join(", ") || "No matches.";
  let guideline = scrbResults.guidelines.map(g => `${g.title} SOP`).join("; ") || "No guideline SOP found.";
  let precedent = scrbResults.precedents.map(p => p.relevant_principle).join("; ") || "No principles matched.";
  let reasoning = "Decisions generated by evaluating timeline and case parameters.";
  let confidence = "Likely";
  let next_action = strategy.immediate_actions?.[0]?.recommendation || "Verify complaint parameters.";

  if (isFollowUp) {
    if (followUpTopic === "reasoning") {
      answer = `Advisory reasoning path details: The recommendation of "${next_action}" is proposed based on active guidelines. Node traces trace the following path: Complaint -> Entities -> Timeline -> Evidence -> Decision.`;
      reasoning = reasoningTree.map(n => n.evidence_trace).join(" -> ");
    } else if (followUpTopic === "more") {
      answer = `Expanding current assessment: Suggested procedure is to immediately document and secure call detail records (CDR) and trace IP logins of siphoning UPI handles.`;
      next_action = "Liaise with Nodal officers to secure suspect gateway logs.";
    } else if (followUpTopic === "contradictions") {
      if (contradictions.length > 0) {
        answer = `Anomalies identified: ${contradictions.map(c => c.contradiction).join(" · ")}. Details: ${contradictions.map(c => c.reason).join(" · ")}.`;
        evidence = contradictions.map(c => c.supporting_evidence).join("; ");
        confidence = "Needs verification";
      } else {
        answer = "No contradictions or timeline conflicts detected.";
      }
    } else if (followUpTopic === "evidence") {
      answer = `Supporting evidence summary: Case cabinet files hold the following indicators. Missing evidence includes ${reliability.missing_evidence.join(", ") || "none"}.`;
      evidence = `Cabinet includes: ${reliability.evidence_scores.map(s => s.name).join(", ") || "None"}.`;
    } else if (followUpTopic === "similar") {
      answer = `Similarity analysis: Matched ${scrbResults.landmarks.length} similar cases. Key MO matches: ${type} fraud patterns siphoning deposit payments via UPI.`;
      next_action = scrbResults.landmarks[0]?.next_steps || "Inspect previous lessons.";
    }
  } else {
    if (query.includes("do next") || query.includes("next step") || query.includes("action")) {
      answer = `Based on case completion indices, the suggested next step is to secure raw evidence logs and acquire missing verification elements.`;
      next_action = strategy.immediate_actions?.[0]?.recommendation || "Conduct officer review.";
    } else if (query.includes("contradiction") || query.includes("conflict")) {
      if (contradictions.length > 0) {
        answer = `The system highlights possible contradiction anomalies in this complaint timeline.`;
        evidence = contradictions.map(c => c.supporting_evidence).join("; ");
      } else {
        answer = "No timeline contradictions detected.";
      }
    } else if (query.includes("evidence") || query.includes("weak")) {
      answer = `Evidence analysis: Cabinet completeness is evaluated. Missing items require collection.`;
      evidence = `Missing: ${reliability.missing_evidence.join(", ") || "none"}`;
    } else if (query.includes("similar") || query.includes("previous")) {
      answer = `The engine identifies similar historical cases registered in the SCRB repository.`;
    } else {
      answer = `Cognitive copilot stands by. Ready to answer follow-up queries on reasoning, timeline contradictions, or missing files.`;
    }
  }

  if (lang === "kn") {
    return {
      answer: `[ಕನ್ನಡ] ${answer}`,
      evidence: `ಪುರಾವೆ: ${evidence}`,
      matches: `ಹೊಂದಾಣಿಕೆಗಳು: ${matches}`,
      guideline: `ಮಾರ್ಗಸೂಚಿ: ${guideline}`,
      precedent: `ಪೂರ್ವನಿದರ್ಶನ: ${precedent}`,
      reasoning: `ತಾರ್ಕಿಕ ವಿವರಣೆ: ${reasoning}`,
      confidence: `ವಿಶ್ವಾಸಾರ್ಹತೆ: ${confidence}`,
      next_action: `ಮುಂದಿನ ಕ್ರಮ: ${next_action}`
    };
  }

  return {
    answer,
    evidence,
    matches,
    guideline,
    precedent,
    reasoning,
    confidence,
    next_action
  };
};

/**
 * Conversational Investigation Copilot with Live Gemini AI Integration & Offline Fallback.
 */
export const askCopilot = async (questionText, currentCase, allCases = [], lang = "en", chatHistory = []) => {
  if (!currentCase) {
    return askCopilotRuleBased(questionText, currentCase, allCases, lang, chatHistory);
  }

  const proxyUrl = import.meta.env.VITE_CATALYST_PROXY_URL || '/server/geminiProxy';

  // Pre-calculate structured context from CrimeLens internal engines
  const scrbResults = searchSCRBRepository(currentCase);
  const strategy = generateInvestigationStrategy(currentCase);
  const contradictions = detectContradictions(currentCase, allCases);
  const reliability = calculateEvidenceReliability(currentCase);
  const reasoningTree = getReasoningTree(currentCase);

  const prompt = `System: You are CrimeLens Copilot, an AI-assisted reasoning layer for the Karnataka State Police (KSP) investigation workspace.

RULES & POLICY:
1. You NEVER solve cases, determine guilt, make legal conclusions, or name suspects as criminals.
2. NEVER use forbidden words: "guilty", "criminal", "solved", "confirmed", "proved", "definitely".
3. Use ONLY advisory and probabilistic language: "suggested", "likely", "possible", "may indicate", "requires verification", "advisory".
4. The CrimeLens internal engines provided below are the primary source of truth. Explain and summarize their findings clearly.
5. ALWAYS remind the user: "The AI assists. The investigating officer remains the final decision maker."
6. Keep response concise (under 250 words).

STRUCTURED CRIMELENS ENGINE OUTPUTS:
- Case ID: ${currentCase.id} (${currentCase.incident_type || 'General'})
- Summary: ${currentCase.summary || 'N/A'}
- Extracted Entities: ${JSON.stringify(currentCase.entities || {})}
- Timeline Events: ${JSON.stringify(currentCase.timeline || [])}
- Historical Landmark Matches: ${JSON.stringify(scrbResults.landmarks.map(l => ({ id: l.id, title: l.title, similarity: l.similarity })))}
- Police Guidelines / SOPs: ${JSON.stringify(scrbResults.guidelines.map(g => g.title))}
- Legal Precedents / Principles: ${JSON.stringify(scrbResults.precedents.map(p => ({ title: p.title, principle: p.relevant_principle })))}
- Strategy Recommendations: ${JSON.stringify(strategy.immediate_actions || [])}
- Contradictions Detected: ${JSON.stringify(contradictions || [])}
- Evidence Reliability / Missing Evidence: ${JSON.stringify(reliability.missing_evidence || [])}
- Reasoning Chain: ${JSON.stringify(reasoningTree.map(r => r.evidence_trace))}

OFFICER QUESTION: "${questionText}"
RESPONSE LANGUAGE: ${lang === 'kn' ? 'Kannada' : 'English'}

Return ONLY a valid JSON object matching this schema. Do NOT use markdown code fences.
{
  "answer": "Concise natural language answer explaining the internal engine findings in advisory terms.",
  "evidence": "Brief list of supporting evidence items.",
  "matches": "${scrbResults.landmarks.map(m => m.id).join(', ') || 'None'}",
  "guideline": "${scrbResults.guidelines.map(g => g.title).join('; ') || 'Standard SOP'}",
  "precedent": "${scrbResults.precedents.map(p => p.relevant_principle).join('; ') || 'Standard Procedure'}",
  "reasoning": "Explanation of the reasoning chain from CrimeLens engines.",
  "confidence": "Likely",
  "next_action": "${strategy.immediate_actions?.[0]?.recommendation || 'Verify complaint parameters.'}"
}`;

  try {
    const res = await fetch(proxyUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        action: 'copilot',
        prompt
      })
    });

    if (!res.ok) throw new Error(`HTTP ${res.status}`);

    const result = await res.json();
    if (result && result.success && result.data) {
      const parsed = result.data;
      return {
        answer: parsed.answer || "Advisory summary available from CrimeLens engines.",
        evidence: parsed.evidence || "Primary complaint logs.",
        matches: parsed.matches || scrbResults.landmarks.map(m => m.id).join(", "),
        guideline: parsed.guideline || scrbResults.guidelines.map(g => `${g.title} SOP`).join("; "),
        precedent: parsed.precedent || scrbResults.precedents.map(p => p.relevant_principle).join("; "),
        reasoning: parsed.reasoning || "Reasoning chain evaluated from parameters.",
        confidence: parsed.confidence || "Likely",
        next_action: parsed.next_action || strategy.immediate_actions?.[0]?.recommendation || "Verify parameters."
      };
    }
  } catch (err) {
    console.warn("[CrimeLens Copilot] Catalyst geminiProxy call failed — falling back to internal rule-based engine:", err.message);
  }

  // Fallback to internal rule-based copilot
  return askCopilotRuleBased(questionText, currentCase, allCases, lang, chatHistory);
};

